apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: '{{ .Values.image }}:{{ .Values.tag | default "latest" }}'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DRINK
              value: {{ .Values.drink }}
          volumeMounts:
            - mountPath: /etc/nginx/templates
              name: simples-config
              readOnly: true
      volumes:
        - name: simples-config
          configMap:
            name: simples-config
            items:
              - key: simples.conf
                path: default.conf.template
